version: '3'

services:
  ipfs.node.1:
    container_name: "ipfs_node_1"
    image: ipfs/go-ipfs:v0.4.23
    command: daemon --migrate=true --enable-namesys-pubsub
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ${PWD}/ipfs/nodes/1/config:/data/ipfs/config
      - ${PWD}/ipfs/nodes/1/version:/data/ipfs/version
      - ${PWD}/ipfs/nodes/1/datastore_spec:/data/ipfs/datastore_spec

  ipfs.cluster.1:
    container_name: "ipfs_cluster_1"
    depends_on: 
      - ipfs.node.1
    image: ipfs/ipfs-cluster:v0.12.1
    ports:
      - 9094:9094
      - 9095:9095
      - 9096:9096
    volumes:
      - ${PWD}/ipfs/clusters/1/service.json:/data/ipfs-cluster/service.json

  postgres:
    image: postgres:10.12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "temporal"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password123"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
